version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  db:
    build: ./db
    environment:
      - POSTGRES_DB=base_datos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
      - ./db/backups:/var/pg/backups
    ports:
      - "5432:5432"
  web:
    build: ./mlp_api
    command: gunicorn -c gunicorn.conf mlp_api.wsgi
    volumes:
      - ./mlp_api:/mlp_api
    ports:
      - "8000:8000"
    env_file:
      - ./mlp_api/.env
    environment:
      PROD: 'true'
    depends_on:
      - db
    links:
      - redis
  nginx:
    build: ./nginx
    depends_on:
      - web
    command: nginx -g 'daemon off;'
    ports:
      - "8090:80"
    volumes:
      - ./mlp_api/static:/mlp_api/static
      - ./mlp_api/media:/mlp_api/media

volumes:
  db_data:
    external: true