version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=base_datos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  web:
    build: ./mlp_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mlp_api:/mlp_api
    ports:
      - "8000:8000"
    env_file:
      - ./mlp_api/.env
    environment:
      PROD: 'false'
    depends_on:
      - db
    links:
      - redis

volumes:
  db_data:
    external: true